spring.application.name=mlb-api
spring.datasource.url=jdbc:postgresql://localhost:5432/mlb_db
spring.datasource.username=mlb_admin
spring.datasource.password=admin_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true